linters:
  disable:
    # Annoying / too strict:
    - gochecknoglobals
    - godox
    - funlen
    - gomnd
    - testpackage
    - wsl
    - lll
    - nlreturn
    - exhaustivestruct
    - wrapcheck
    - gocritic
    # Unrelated (http linters):
    - bodyclose
    - noctx
  presets:
    - bugs
    - performance
    - style
    - unused
