linters:
  disable:
    - gochecknoglobals
    - godox
    - funlen
    - gomnd
    - testpackage
    - wsl
    - lll
  presets:
    - bugs
    - style
    - unused

linter-settings:
  lll:
    line-length: 120
    tab-width: 4
